# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0002_profile_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_token',
            field=models.CharField(default=uuid.UUID('7e004d70-c612-40ca-b007-bfd5dc7186a1'), max_length=64),
        ),
    ]
