# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0004_auto_20180923_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activation_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
